# Generated by Django 5.2.6 on 2025-09-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
