# Generated by Django 5.2.6 on 2025-09-07 12:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_projectcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the main portfolio page.'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(help_text="A unique, URL-friendly version of the name, e.g., 'web-design'.", max_length=255),
        ),
    ]
