# Generated by Django 5.2.6 on 2025-09-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_projectpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='thumbnail_image',
            field=models.ForeignKey(help_text='Thumbnail image for the main portfolio grid (9:16 ratio).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='preview_image',
            field=models.ForeignKey(blank=True, help_text='Image used on the project detail page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
