# Generated by Django 5.2.6 on 2025-09-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projectpage_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='search_description',
            field=models.TextField(blank=True, help_text='Optional. The short description displayed in search engine results.'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional. The title displayed in search engine results and browser tabs. If empty, the category name will be used.', max_length=255),
        ),
    ]
