# Generated by Django 5.2.6 on 2025-09-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projectcategory_search_description_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='preview_video',
            field=models.ForeignKey(blank=True, help_text='Видео на странице проекта (имеет приоритет над изображением).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='thumbnail_video',
            field=models.ForeignKey(blank=True, help_text='Видео для сетки (имеет приоритет над изображением).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='preview_image',
            field=models.ForeignKey(blank=True, help_text='Изображение на странице проекта (если не выбрано видео).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Изображение для сетки (если не выбрано видео).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
