# Generated by Django 5.2.6 on 2025-09-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_projectpage_preview_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='videos')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='preview_video',
            field=models.ForeignKey(blank=True, help_text='Видео на странице проекта (имеет приоритет над изображением).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.video'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='thumbnail_video',
            field=models.ForeignKey(blank=True, help_text='Видео для сетки (имеет приоритет над изображением).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.video'),
        ),
    ]
