# Generated by Django 5.2.6 on 2025-09-08 18:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='preview_video',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Заголовок', 'template': 'blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Параграф', 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Изображение', 'template': 'blocks/image_block.html'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись к видео', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('video', 3), ('caption', 4)]], {'icon': 'media', 'label': 'Видео', 'template': 'blocks/video_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
