# Generated by Django 5.2.6 on 2025-09-09 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_projectpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 5), ('gallery', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'title', 'label': 'Heading', 'template': 'blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Paragraph', 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('video', 3), ('caption', 4)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'grip', 'label': 'Image Gallery (2 to 4 images)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/image_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
