# Generated by Django 5.2.6 on 2025-09-12 18:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='main_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Главный текст, который будет отображаться при выборе этой категории.'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='secondary_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Второстепенный текст, который будет отображаться при выборе этой категории.'),
        ),
    ]
