# Generated by Django 5.2.6 on 2025-09-12 19:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_projectcategory_main_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 5), ('gallery', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'title', 'label': 'Heading', 'template': 'blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Paragraph', 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('video', 3), ('caption', 4)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')], 'label': 'Media Type'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'label': 'Video', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('media_type', 6), ('image', 7), ('video', 8)]], {'label': 'Gallery Item'}), 10: ('wagtail.blocks.ListBlock', (9,), {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
