# Generated by Django 5.2.6 on 2025-09-13 16:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_projectpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 5), ('head_card', 14), ('gallery', 15)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'title', 'label': 'Heading', 'template': 'blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Paragraph', 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('video', 3), ('caption', 4)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video'}), 8: ('wagtail.blocks.StreamBlock', [[('image', 6), ('video', 7)]], {'label': 'Media (Image or Video)', 'max_num': 1, 'min_num': 1}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Project Name', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Industry', 'required': True}), 11: ('wagtail.blocks.DateBlock', (), {'label': 'Completed Date', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'GET STARTED', 'label': 'CTA Button Text'}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'CTA Button URL', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('media', 8), ('project_name', 9), ('industry', 10), ('completed', 11), ('cta_text', 12), ('cta_url', 13)]], {'icon': 'user', 'label': 'Head Card', 'template': 'blocks/head_card_block.html'}), 15: ('wagtail.blocks.StreamBlock', [[('image', 6), ('video', 7)]], {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
