# Generated by Django 5.2.6 on 2025-09-14 06:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_projectpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('add_text', 3), ('image', 4), ('video', 7), ('card_head', 14), ('card_head_2', 19), ('gallery', 20)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Heading', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment'}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraph', 1), ('text_align', 2)]], {'icon': 'doc-full', 'label': 'Add Text', 'template': 'blocks/add_text_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('video', 5), ('caption', 6)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video'}), 10: ('wagtail.blocks.StreamBlock', [[('image', 8), ('video', 9)]], {'label': 'Media (Image or Video)', 'max_num': 1, 'min_num': 1}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Project Name', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Industry', 'required': True}), 13: ('wagtail.blocks.DateBlock', (), {'label': 'Completed Date', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('media', 10), ('project_name', 11), ('industry', 12), ('completed_date', 13)]], {'icon': 'doc-full', 'label': 'Card Head', 'template': 'blocks/card_head_block.html'}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Title PNG Image', 'required': True}), 16: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Contact Us', 'label': 'Contact Button Text', 'required': True}), 18: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'label': 'Main Video', 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('title_png', 15), ('paragraph', 16), ('contact_button_text', 17), ('video', 18), ('project_name', 11), ('industry', 12), ('completed_date', 13)]], {'icon': 'doc-full', 'label': 'Card Head 2', 'template': 'blocks/card_head_2_block.html'}), 20: ('wagtail.blocks.StreamBlock', [[('image', 8), ('video', 9)]], {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
