# Generated by Django 5.2.6 on 2025-09-15 13:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_projectpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Включить контактный виджет')),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('top-right', 'Top Right'), ('top-left', 'Top Left')], default='bottom-right', help_text='Позиция виджета на странице', max_length=20)),
                ('main_icon', models.CharField(default='send.svg', help_text='Иконка главной кнопки (например: send.svg). Должна лежать в /static/contact/', max_length=100)),
                ('animation_speed', models.FloatField(default=0.3, help_text='Скорость анимации в секундах')),
                ('show_tooltip', models.BooleanField(default=True, help_text='Показывать подсказку при наведении')),
                ('tooltip_text', models.CharField(default='Contact us', help_text='Текст подсказки', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Widget',
                'verbose_name_plural': 'Contact Widgets',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название социальной сети', max_length=100)),
                ('network_type', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('custom', 'Custom')], default='custom', help_text='Тип социальной сети для автоматического определения иконки', max_length=20)),
                ('url', models.URLField(help_text='Ссылка на профиль/канал')),
                ('icon', models.CharField(default='send.svg', help_text='Имя файла иконки (например: instagram.svg). Должен лежать в /static/contact/', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли эту социальную сеть')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)')),
                ('open_in_new_tab', models.BooleanField(default=True, help_text='Открывать ссылку в новой вкладке')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('add_text', 3), ('image', 4), ('video', 7), ('card_head', 14), ('card_head_2', 16), ('gallery', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Heading', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment'}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraph', 1), ('text_align', 2)]], {'icon': 'doc-full', 'label': 'Add Text', 'template': 'blocks/add_text_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('video', 5), ('caption', 6)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video'}), 10: ('wagtail.blocks.StreamBlock', [[('image', 8), ('video', 9)]], {'label': 'Media (Image or Video)', 'max_num': 1, 'min_num': 1}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Project Name', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Industry', 'required': True}), 13: ('wagtail.blocks.DateBlock', (), {'label': 'Completed Date', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('media', 10), ('project_name', 11), ('industry', 12), ('completed_date', 13)]], {'icon': 'doc-full', 'label': 'Card Head', 'template': 'blocks/card_head_block.html'}), 15: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('video', 15), ('project_name', 11)]], {'icon': 'doc-full', 'label': 'Card Head 2', 'template': 'blocks/card_head_2_block.html'}), 17: ('wagtail.blocks.StreamBlock', [[('image', 8), ('video', 9)]], {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
