# Generated by Django 5.2.6 on 2025-09-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_contactwidget_socialnetwork_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='widget',
            field=models.ForeignKey(default=1, help_text='Виджет, к которому относится эта социальная сеть', on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='home.contactwidget'),
        ),
    ]
