# Generated by Django 5.2.6 on 2025-09-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_socialnetwork_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='widget',
            field=models.ForeignKey(help_text='Виджет, к которому относится эта социальная сеть', on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='home.contactwidget'),
        ),
    ]
