# Generated by Django 5.2.6 on 2025-09-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_socialnetwork_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='widget',
        ),
        migrations.DeleteModel(
            name='ContactWidget',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
