# Generated by Django 5.2.6 on 2025-09-16 10:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_socialnetwork_widget_delete_contactwidget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('add_text', 3), ('image', 4), ('video', 7), ('card_head_2', 10), ('gallery', 13)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Heading', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment'}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraph', 1), ('text_align', 2)]], {'icon': 'doc-full', 'label': 'Add Text', 'template': 'blocks/add_text_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 5: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('video', 5), ('caption', 6)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Project Name', 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('video', 8), ('project_name', 9)]], {'icon': 'doc-full', 'label': 'Card Head 2', 'template': 'blocks/card_head_2_block.html'}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 12: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video'}), 13: ('wagtail.blocks.StreamBlock', [[('image', 11), ('video', 12)]], {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
