# Generated by Django 5.2.6 on 2025-09-16 12:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_add_2_1_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('add_text', 3), ('image', 4), ('image_2_1', 5), ('video', 8), ('video_2_1', 9), ('card_head_2', 16), ('gallery', 19)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Heading', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment'}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraph', 1), ('text_align', 2)]], {'icon': 'doc-full', 'label': 'Add Text', 'template': 'blocks/add_text_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image', 'template': 'blocks/image_block.html'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image 2:1', 'template': 'blocks/image_2_1_block.html'}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Caption', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('video', 6), ('caption', 7)]], {'icon': 'media', 'label': 'Video', 'template': 'blocks/video_block.html'}), 9: ('wagtail.blocks.StructBlock', [[('video', 6), ('caption', 7)]], {'icon': 'media', 'label': 'Video 2:1', 'template': 'blocks/video_2_1_block.html'}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Project Name', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Year', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Industry', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Client Name', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Client URL (optional)', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('video', 10), ('project_name', 11), ('year', 12), ('industry', 13), ('client_name', 14), ('client_url', 15)]], {'icon': 'doc-full', 'label': 'Card Head 2', 'template': 'blocks/card_head_2_block.html'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 18: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Video',), {'icon': 'media', 'label': 'Video'}), 19: ('wagtail.blocks.StreamBlock', [[('image', 17), ('video', 18)]], {'icon': 'grip', 'label': 'Media Gallery (2 to 4 items)', 'max_num': 4, 'min_num': 2, 'template': 'blocks/mixed_gallery_block.html'})}, help_text='Основной контент страницы, собираемый из блоков.'),
        ),
    ]
