# Generated by Django 5.2.6 on 2025-09-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_add_card_head_2_fields'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='thumbnail_video',
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Изображение для сетки (если не выбрано видео в Card Head 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
