# Generated by Django 5.2.6 on 2025-09-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_infoindexpage_infopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='InfoIndexPage',
        ),
        migrations.DeleteModel(
            name='InfoPage',
        ),
    ]
