# Generated by Django 5.2.6 on 2025-09-17 10:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_infoindexpage_infopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='description',
        ),
        migrations.AddField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main content of the info page.'),
        ),
        migrations.AlterField(
            model_name='infoindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the info section.'),
        ),
    ]
