# Generated by Django 5.2.6 on 2025-09-17 10:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_infopage_description_infopage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Вводный текст для раздела Information Pages.'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Основной контент информационной страницы.'),
        ),
    ]
