# Generated by Django 5.2.6 on 2025-09-22 14:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_cardsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='widget',
        ),
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Вводный текст для главной страницы портфолио.'),
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='CardsIndexPage',
        ),
        migrations.DeleteModel(
            name='ContactWidget',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
