# Generated by Django 5.2.6 on 2025-09-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_button_icon', models.FileField(default='contact_icons/send.svg', help_text='SVG иконка для основной кнопки виджета (по умолчанию send.svg)', upload_to='contact_icons/', verbose_name='Иконка основной кнопки')),
                ('widget_enabled', models.BooleanField(default=True, help_text='Показывать ли контактный виджет на сайте', verbose_name='Включить виджет')),
                ('position', models.CharField(choices=[('bottom-right', 'Правый нижний угол'), ('bottom-left', 'Левый нижний угол')], default='bottom-right', help_text='Позиция виджета на странице', max_length=20, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки контактов',
                'verbose_name_plural': 'Настройки контактов',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название социальной сети (например: Instagram, Telegram)', max_length=50, verbose_name='Название')),
                ('icon', models.FileField(help_text='SVG иконка для социальной сети', upload_to='contact_icons/', verbose_name='Иконка')),
                ('url', models.URLField(help_text='Полная ссылка на профиль/канал', verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли эту ссылку в виджете', verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше число = выше в списке)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_button_icon', models.FileField(default='contact_icons/send.svg', help_text='SVG иконка для основной кнопки виджета (по умолчанию send.svg)', upload_to='contact_icons/', verbose_name='Иконка основной кнопки')),
                ('widget_enabled', models.BooleanField(default=True, help_text='Показывать ли контактный виджет на сайте', verbose_name='Включить виджет')),
                ('position', models.CharField(choices=[('bottom-right', 'Правый нижний угол'), ('bottom-left', 'Левый нижний угол')], default='bottom-right', help_text='Позиция виджета на странице', max_length=20, verbose_name='Позиция')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки контактов',
                'verbose_name_plural': 'Настройки контактов',
            },
        ),
    ]
