# Generated by Django 5.2.6 on 2025-09-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSettings',
        ),
    ]
