# Generated by Django 5.2.6 on 2025-09-15 16:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_delete_contactsettings'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название проекта для отображения на сайте', max_length=200, verbose_name='Название проекта')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Описание проекта', verbose_name='Описание')),
                ('category', models.CharField(help_text='Категория проекта (например: Web, Mobile, Design)', max_length=100, verbose_name='Категория')),
                ('client', models.CharField(blank=True, help_text='Название клиента или компании', max_length=200, verbose_name='Клиент')),
                ('project_url', models.URLField(blank=True, help_text='Ссылка на живой проект или демо', verbose_name='Ссылка на проект')),
                ('github_url', models.URLField(blank=True, help_text='Ссылка на репозиторий GitHub', verbose_name='GitHub')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать ли проект в рекомендуемых', verbose_name='Рекомендуемый')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли проект на сайте', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше число = выше в списке)', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_image', models.ForeignKey(help_text='Основное изображение проекта', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Миниатюра')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
