# Generated by Django 5.2.6 on 2025-09-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
