[phases.setup]
nixPkgs = ["python", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd mysite && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
