[build]
builder = "NIXPACKS"

[deploy]
# This command executes the deployment script.
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 150
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
